name    'rtyler-sauceconnect'
version '2.0.0'
source 'https://github.com/rtyler/puppet-sauceconnect'
author 'rtyler'
license 'Apache License, Version 2.0'
summary 'Simple module for managing a machine-wide Sauce Connect tunnel'
description 'This is the sauceconnect module, it will manage running a Sauce Connect tunnel daemon on a host for you.'
project_page 'https://github.com/rtyler/puppet-sauceconnect'
